spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://13.209.98.146:3306/chatproject?characterEncoding=UTF-8&serverTimezone=UTC
    username : root
    password : Odudals753!

login:
  naver:
     client-id : UJDafTNvyeDfOJNTsIpV
     client-secret : XqTYM5w7N6
     get-token-url : https://nid.naver.com/oauth2.0/token?grant_type=authorization_code
     get-detail-url :  https://openapi.naver.com/v1/nid/me